version: '3'
services:
    web:
      build: .
      volumes:
        - /usr/src/app
      ports:
        - "3000:3000"
      depends_on:
        - mongo
    mongo:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - /data/db